FROM intel/deep-learning-essentials:2025.1.3-0-devel-ubuntu24.04 AS vllm-base

ENV DEBIAN_FRONTEND=noninteractive
ARG BUILD_ENV=docker
ENV BUILD_ENV=${BUILD_ENV}

# Remove uncessary packages in base image
RUN apt-get remove -y libze-intel-gpu1 \
    libigc1 \
    libigdfcl1 \
    libze-dev

# Install all dependencies required to run the installer
RUN apt-get update && apt-get install -y --no-install-recommends \
    systemd \
    pciutils \
    iproute2 \
    net-tools \
    sudo \
    vim \
    curl \
    wget \
    bash-completion \
    locales \
    dbus \
    libdrm2 \
    libpciaccess0 \
    libx11-6 \
    libxml2 \
    libnl-3-200 \
    libnl-route-3-200 \
    libnuma1 \
    libxext6 \
    xz-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN set -eux; \
    mkdir -p /opt/intel/multi-arc; \
    cd /tmp; \
    wget https://sourceforge.net/projects/analytics-zoo/files/vllm-scaler/offline-installer/bmg/multi-arc-bmg-offline-installer-25.38.4.1.tar.xz/download -O multi-arc-bmg-offline-installer.tar.xz; \
    mv /tmp/*.tar.xz /opt/intel/multi-arc/; \
    cd /opt/intel/multi-arc && \
    xz -d *.tar.xz && \
    tar -xvf *.tar && \
    cd multi-arc-bmg-offline-installer-* && \
    chmod +x installer.sh && \
    ./installer.sh && \
    cd / && \
    rm -rf /opt/intel/multi-arc/*.tar && \
    rm -rf /opt/intel/multi-arc/oneapi/*.sh && \
    rm -rf /opt/intel/multi-arc/multi-arc-bmg-offline-installer-*/*.sh

# Set up UTF-8 locale
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Systemd support
STOPSIGNAL SIGRTMIN+3
CMD ["/lib/systemd/systemd"]
